import{S as u,a as y,i as c}from"./assets/vendor-BH9GyP-n.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const a={form:document.querySelector(".form"),input:document.querySelector("#input"),button:document.querySelector(".button-search"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader-text")};let f=new u(".gallery a",{captionsData:"alt",captionDelay:250});async function h(o){const r="https://pixabay.com/api/",i={key:"49636460-73c540aa8750c0befabaf1348",q:o,image_type:"photo",orientation:"horizontal",safesearch:"true"};try{const{data:e}=await y.get(r,{params:i});return e.hits.length===0?(c.info({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),l(),a.gallery.classList.add("hidden"),null):(a.input.value="",d(),b(e.hits),l(),f.refresh(),e.hits)}catch(e){return l(),c.error({title:"Error",message:`❌ Error fetching images: ${e.message}. Please try again!`,position:"topRight"}),null}}const L=new u(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){const r=o.map(s=>{const{largeImageURL:i,webformatURL:e,tags:t,likes:n,views:p,comments:g,downloads:m}=s;return`<li class="gallery-item">
              <a class="gallery-link" href="${i}">
                <img class="gallery-image" src="${e}" alt="${t}" />
              </a>
              <div class="info">
                <p>Likes: <span class="likes">${n}</span></p>
                <p>Views: <span class="views">${p}</span></p>
                <p>Comments: <span class="comments">${g}</span></p>
                <p>Downloads: <span class="downloads">${m}</span></p>
              </div>
            </li>`}).join("");a.gallery.innerHTML=r,L.destroy()}function d(){a.gallery.innerHTML=""}function w(){a.gallery.classList.add("hidden")}function l(){a.gallery.classList.remove("hidden")}a.form.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements.input.value.trim();if(w(),!r){l(),c.error({title:"Error",message:"Please enter a search query.",position:"topRight"}),a.gallery.classList.add("hidden");return}d();const s=await h(r);s&&s.length>0&&c.success({title:"Success",message:`Found ${s.length} images for your query!`,position:"topRight"}),l()});
//# sourceMappingURL=index.js.map
